In [38]:
import os
import sys
if os.getcwd().endswith("notebooks"):
    os.chdir("..")

sys.path.append(os.getcwd())

In [39]:
from src.components.data_ingestion import DataIngestion

ingestion = DataIngestion()
df = ingestion.initiate_data_ingestion()

df.head()

[*********************100%***********************]  503 of 503 completed

,date,symbol,adj close,close,high,low,open,volume
0,2015-01-02,A,36.899387,40.560001,41.310001,40.369999,41.180000,1529200.0
1,2015-01-02,AAPL,24.192598,27.332500,27.860001,26.837500,27.847500,212818400.0
2,2015-01-02,ABBV,41.411915,65.889999,66.400002,65.440002,65.440002,5086100.0
3,2015-01-02,ABNB,NaN,NaN,NaN,NaN,NaN,NaN
4,2015-01-02,ABT,36.009201,44.900002,45.450001,44.639999,45.250000,3216600.0

In [40]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [41]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1454173 entries, 0 to 1454172
Data columns (total 8 columns):
 #   Column     Non-Null Count    Dtype
---  ------     --------------    -----
 0   date       1454173 non-null  datetime64[ns]
 1   symbol     1454173 non-null  object
 2   adj close  1399123 non-null  float64
 3   close      1399123 non-null  float64
 4   high       1399123 non-null  float64
 5   low        1399123 non-null  float64
 6   open       1399123 non-null  float64
 7   volume     1399123 non-null  float64
dtypes: datetime64[ns](1), float64(6), object(1)
memory usage: 88.8+ MB

In [42]:
df.describe()

,date,adj close,close,high,low,open,volume
count,1454173,1.399123e+06,1.399123e+06,1.399123e+06,1.399123e+06,1.399123e+06,1.399123e+06
mean,2020-09-29 10:35:34.347976448,1.261371e+02,1.346032e+02,1.361583e+02,1.329875e+02,1.345871e+02,6.630146e+06
min,2015-01-02 00:00:00,4.586973e-01,4.785000e-01,4.875000e-01,4.735000e-01,4.812500e-01,0.000000e+00
25%,2017-11-13 00:00:00,3.981326e+01,4.617000e+01,4.672000e+01,4.560000e+01,4.616000e+01,1.045700e+06
50%,2020-09-29 00:00:00,7.404337e+01,8.293000e+01,8.384000e+01,8.200000e+01,8.293000e+01,2.244800e+06
75%,2023-08-15 00:00:00,1.397345e+02,1.511400e+02,1.528604e+02,1.493700e+02,1.511100e+02,5.231400e+06
max,2026-07-02 00:00:00,9.924400e+03,9.924400e+03,9.964770e+03,9.794000e+03,9.914170e+03,3.692928e+09
std,NaN,2.679648e+02,2.685744e+02,2.718132e+02,2.653465e+02,2.685570e+02,2.661970e+07

In [43]:
df.shape

(1454173, 8)

In [44]:
df.columns

Index(['date', 'symbol', 'adj close', 'close', 'high', 'low', 'open',
       'volume'],
      dtype='object')

In [45]:
df.duplicated(subset=['symbol', 'date']).sum()

np.int64(0)

In [46]:
df.isnull().sum()

date             0
symbol           0
adj close    55050
close        55050
high         55050
low          55050
open         55050
volume       55050
dtype: int64

In [47]:
df[df['close'].isna()].sample(10)

              date symbol  adj close  close  high  low  open  volume
393251  2018-02-08   SNDK        NaN    NaN   NaN  NaN   NaN     NaN
495494  2018-11-29    APP        NaN    NaN   NaN  NaN   NaN     NaN
1336352 2025-07-28      Q        NaN    NaN   NaN  NaN   NaN     NaN
521230  2019-02-14   CTVA        NaN    NaN   NaN  NaN   NaN     NaN
596185  2019-09-18   DDOG        NaN    NaN   NaN  NaN   NaN     NaN
135762  2016-01-28   UBER        NaN    NaN   NaN  NaN   NaN     NaN
573459  2019-07-16    APP        NaN    NaN   NaN  NaN   NaN     NaN
484392  2018-10-29   ABNB        NaN    NaN   NaN  NaN   NaN     NaN
374878  2017-12-15    DOW        NaN    NaN   NaN  NaN   NaN     NaN
101729  2015-10-21   CVNA        NaN    NaN   NaN  NaN   NaN     NaN

VICI, VLTO, CARR, CPAY, SNDK Many of these weren't publicly traded during some of the dates in the dataset.
this means companies that didn't exist or weren't listed during the earlier years, the data source returns NaN for those dates.

In [48]:
#check how much data is missing for each company
missing_counts = (
    df.groupby('symbol')['close']
      .apply(lambda x: x.isna().sum())
      .sort_values(ascending=False)
)

print(missing_counts.head(20))

symbol
BNY     2891
HONA    2878
FDXF    2865
Q       2720
SNDK    2544
GEV     2323
SOLV    2322
VLTO    2203
KVUE    2098
GEHC    2003
CEG     1774
HOOD    1654
APP     1581
COIN    1580
EXE     1537
ABNB    1496
DASH    1495
PLTR    1446
CARR    1311
OTIS    1311
Name: close, dtype: int64