In [43]:
import os
import sys
if os.getcwd().endswith("notebooks"):
    os.chdir("..")

sys.path.append(os.getcwd())

In [44]:
import pandas as pd
import glob
import os

In [45]:
df_apple=pd.read_csv("data/AAPL.csv",)
df_amazon=pd.read_csv("data/AMZN.csv")
df_google=pd.read_csv("data/GOOGL.csv")
df_infosys=pd.read_csv("data/INFY_NS.csv")
df_meta=pd.read_csv("data/META.csv")
df_microsoft=pd.read_csv("data/MSFT.csv")
df_nvdia=pd.read_csv("data/NVDA.csv")
df_reliance=pd.read_csv("data/RELIANCE_NS.csv")
df_tcs=pd.read_csv("data/TCS_NS.csv")
df_tesla=pd.read_csv("data/TSLA.csv")


df_apple.head()

,Date,Adj Close,Close,High,Low,Open,Volume,Symbol
0,2015-01-02,24.192600,27.332500,27.860001,26.837500,27.847500,212818400,AAPL
1,2015-01-05,23.511057,26.562500,27.162500,26.352501,27.072500,257142000,AAPL
2,2015-01-06,23.513273,26.565001,26.857500,26.157499,26.635000,263188400,AAPL
3,2015-01-07,23.842981,26.937500,27.049999,26.674999,26.799999,160423600,AAPL
4,2015-01-08,24.759077,27.972500,28.037500,27.174999,27.307501,237458000,AAPL

In [46]:
df_amazon.head()

         Date  Adj Close    Close     High      Low     Open    Volume Symbol
0  2015-01-02    15.4260  15.4260  15.7375  15.3480  15.6290  55664000   AMZN
1  2015-01-05    15.1095  15.1095  15.4190  15.0425  15.3505  55484000   AMZN
2  2015-01-06    14.7645  14.7645  15.1500  14.6190  15.1120  70380000   AMZN
3  2015-01-07    14.9210  14.9210  15.0640  14.7665  14.8750  52806000   AMZN
4  2015-01-08    15.0230  15.0230  15.1570  14.8055  15.0160  61768000   AMZN

In [47]:
df_google.head()

,Date,Adj Close,Close,High,Low,Open,Volume,Symbol
0,2015-01-02,26.244783,26.477501,26.790001,26.393999,26.629999,26480000,GOOGL
1,2015-01-05,25.744715,25.973000,26.399500,25.887501,26.357500,41182000,GOOGL
2,2015-01-06,25.109346,25.332001,26.060499,25.277500,26.025000,54456000,GOOGL
3,2015-01-07,25.035505,25.257500,25.574499,25.182501,25.547501,46918000,GOOGL
4,2015-01-08,25.122730,25.345501,25.375000,24.750999,25.075500,73054000,GOOGL

In [48]:
df_infosys.head()

,Date,Adj Close,Close,High,Low,Open,Volume,Symbol
0,2015-01-01,359.981018,493.600006,495.500000,489.225006,492.237488,2002764,INFY.NS
1,2015-01-02,367.055237,503.299988,504.762512,493.000000,493.000000,6778320,INFY.NS
2,2015-01-05,363.900970,498.975006,507.500000,494.375000,502.475006,9937024,INFY.NS
3,2015-01-06,356.298096,488.549988,496.250000,483.524994,495.000000,9667316,INFY.NS
4,2015-01-07,358.002838,490.887512,493.687500,487.500000,491.250000,7249916,INFY.NS

In [49]:
df_meta.head()

,Date,Adj Close,Close,High,Low,Open,Volume,Symbol
0,2015-01-02,77.767075,78.449997,78.930000,77.699997,78.580002,18177500,META
1,2015-01-05,76.518059,77.190002,79.250000,76.860001,77.980003,26452200,META
2,2015-01-06,75.487114,76.150002,77.589996,75.360001,77.230003,27399300,META
3,2015-01-07,75.487114,76.150002,77.360001,75.820000,76.760002,22045300,META
4,2015-01-08,77.499435,78.180000,78.230003,76.080002,76.739998,23961000,META

In [50]:
df_microsoft.head()

,Date,Adj Close,Close,High,Low,Open,Volume,Symbol
0,2015-01-02,39.681736,46.759998,47.419998,46.540001,46.660000,27913900,MSFT
1,2015-01-05,39.316837,46.330002,46.730000,46.250000,46.369999,39673900,MSFT
2,2015-01-06,38.739769,45.650002,46.750000,45.540001,46.380001,36447900,MSFT
3,2015-01-07,39.231983,46.230000,46.459999,45.490002,45.980000,29114100,MSFT
4,2015-01-08,40.386093,47.590000,47.750000,46.720001,46.750000,29645200,MSFT

In [51]:
df_nvdia.head()

         Date  Adj Close    Close     High      Low     Open     Volume Symbol
0  2015-01-02   0.482423  0.50325  0.50700  0.49525  0.50325  113680000   NVDA
1  2015-01-05   0.474275  0.49475  0.50475  0.49250  0.50325  197952000   NVDA
2  2015-01-06   0.459896  0.47975  0.49600  0.47925  0.49550  197764000   NVDA
3  2015-01-07   0.458697  0.47850  0.48750  0.47700  0.48325  321808000   NVDA
4  2015-01-08   0.475952  0.49650  0.49950  0.48375  0.48400  283780000   NVDA

In [52]:
df_reliance.head()

,Date,Adj Close,Close,High,Low,Open,Volume,Symbol
0,2015-01-01,189.125336,202.959000,203.896194,201.987518,202.593277,2963643,RELIANCE.NS
1,2015-01-02,188.624802,202.421829,204.821960,202.136108,203.004715,7331366,RELIANCE.NS
2,2015-01-05,186.558670,200.204575,203.644760,199.804550,202.296112,10103941,RELIANCE.NS
3,2015-01-06,178.091812,191.118393,199.553116,190.181198,198.867371,18627980,RELIANCE.NS
4,2015-01-07,181.968491,195.278610,196.307236,191.324127,191.346985,20720312,RELIANCE.NS

In [53]:
df_tcs.head()

,Date,Adj Close,Close,High,Low,Open,Volume,Symbol
0,2015-01-01,975.650879,1272.775024,1283.500000,1270.500000,1283.500000,366830,TCS.NS
1,2015-01-02,988.643738,1289.724976,1295.474976,1275.300049,1275.500000,925740,TCS.NS
2,2015-01-05,973.619385,1270.125000,1299.949951,1262.324951,1290.500000,1754242,TCS.NS
3,2015-01-06,937.725708,1223.300049,1264.550049,1220.000000,1264.550049,2423784,TCS.NS
4,2015-01-07,926.648865,1208.849976,1239.574951,1203.724976,1235.000000,2636332,TCS.NS

In [54]:
df_tesla.head()

,Date,Adj Close,Close,High,Low,Open,Volume,Symbol
0,2015-01-02,14.620667,14.620667,14.883333,14.217333,14.858000,71466000,TSLA
1,2015-01-05,14.006000,14.006000,14.433333,13.810667,14.303333,80527500,TSLA
2,2015-01-06,14.085333,14.085333,14.280000,13.614000,14.004000,93928500,TSLA
3,2015-01-07,14.063333,14.063333,14.318667,13.985333,14.223333,44526000,TSLA
4,2015-01-08,14.041333,14.041333,14.253333,14.000667,14.187333,51637500,TSLA

In [55]:
files = glob.glob("data/*.csv")
dfs = []

for file in files:
    df = pd.read_csv(file)
    dfs.append(df)

merged_df = pd.concat(dfs, ignore_index=True)

In [56]:
merged_df.head()

,Date,Adj Close,Close,High,Low,Open,Volume,Symbol
0,2015-01-02,24.192600,27.332500,27.860001,26.837500,27.847500,212818400,AAPL
1,2015-01-05,23.511057,26.562500,27.162500,26.352501,27.072500,257142000,AAPL
2,2015-01-06,23.513273,26.565001,26.857500,26.157499,26.635000,263188400,AAPL
3,2015-01-07,23.842981,26.937500,27.049999,26.674999,26.799999,160423600,AAPL
4,2015-01-08,24.759077,27.972500,28.037500,27.174999,27.307501,237458000,AAPL

In [57]:
merged_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25013 entries, 0 to 25012
Data columns (total 8 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Date       25013 non-null  object
 1   Adj Close  25013 non-null  float64
 2   Close      25013 non-null  float64
 3   High       25013 non-null  float64
 4   Low        25013 non-null  float64
 5   Open       25013 non-null  float64
 6   Volume     25013 non-null  int64
 7   Symbol     25013 non-null  object
dtypes: float64(5), int64(1), object(2)
memory usage: 1.5+ MB